#!/bin/bash

code=0
FILES=*.i

for f in $FILES; do
	echo "RUNNING $f"
	if ../i $f; then
		echo -e "\e[00;32mOK $f\e[00m"
	else
		echo -e "\e[00;31mERROR $f\e[00m"
		code=1
	fi
done

if [ $code -ne 0 ]; then
	echo -e "\e[00;31mOne or more tests have failed\e[00m"
else
	echo -e "\e[00;32mAll test have passed\e[00m"
fi

exit $code
