#!/bin/bash

code=0
FILES=*.i
BFILES=*.i.bad
SHFILES=*.sh
FAILED=""

rm -rf DB/

for f in $FILES; do
	echo "RUNNING $f"
	echo "RUNNING $f" > .running
	if ../i $f; then
		echo -e "\e[00;32mOK $f\e[00m"
	else
		echo -e "\e[00;31mERROR $f\e[00m"
		code=$(( $code + 1 ))
		FAILED="$FAILED\t$f\n"
	fi
done

for f in $BFILES; do
	echo "RUNNING $f"
	echo "RUNNING $f" > .running
	if ../i $f; then
		echo -e "\e[00;31mERROR $f\e[00m"
		code=$(( $code + 1 ))
		FAILED="$FAILED\t$f\n"
	else
		echo -e "\e[00;32mOK $f\e[00m"
	fi
done

alias i='../i'

for f in $SHFILES; do
	echo "RUNNING $f"
	echo "RUNNING $f" > .running
	if bash ./$f; then
	    echo -e "\e[00;32mOK $f\e[00m"
	else
	    echo -e "\e[00;31mERROR $f\e[00m"
	    code=$(( $code + 1 ))
	    FAILED="$FAILED\t$f\n"
	fi
done

rm .running

if [ $code -ne 0 ]; then
	echo -e "\e[00;31mOne or more tests have failed\e[00m"
	echo -e "$FAILED"
else
	echo -e "\e[00;32mAll test have passed\e[00m"
fi

exit $code
